version: '3.4'
services:
  aria2:
    build:
      context: ./aria2
      args:
        ARIA2_SECRET: ${ARIA2_SECRET}
    ports:
      - "6800:6800"

  webui:
    build:
      context: ./webui
      target: client
      args:
        ARIA2_SECRET: ${ARIA2_SECRET}
        HTPASSWD_USER: ${HTPASSWD_USER}
        HTPASSWD_PASSWORD: ${HTPASSWD_PASSWORD}
    ports:
      - "80:80"
