version: '3.4'
services:
  aria2:
    build:
      context: ./aria2
      args:
        UID: ${UID}
        GID: ${GID}
        ARIA2_SECRET: ${ARIA2_SECRET}
    volumes:
      - ${DATA_DIR}:/home/aria2
    ports:
      - "6800:6800"

  webui:
    build:
      context: ./webui
      target: client
      args:
        ARIA2_SECRET: ${ARIA2_SECRET}
        HTPASSWD_USER: ${HTPASSWD_USER}
        HTPASSWD_PASSWORD: ${HTPASSWD_PASSWORD}
    volumes:
      - ${DATA_DIR}:/var/www/downloads
    ports:
      - "80:80"
