version: '3.4'
services:
  aria2:
    build:
      context: ./aria2
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ${DATA_DIR}:/home/aria2
    restart: on-failure

  webui:
    build:
      context: ./webui
      target: client
      args:
        HTPASSWD_USER: ${HTPASSWD_USER}
        HTPASSWD_PASSWORD: ${HTPASSWD_PASSWORD}
        CERT_DOMAIN: ${CERT_DOMAIN}
        CERT_PASSWORD: ${CERT_PASSWORD}
    volumes:
      - ${DATA_DIR}:/var/www/downloads
    ports:
      - "443:443"
    restart: on-failure
