version: '3.4'
services:
  aria2:
    build:
      context: ./aria2
      args:
        SECRET: ${SECRET}
    ports:
      - "6800:6800"

  webui:
    build:
      context: ./webui
      target: client
      args:
        SECRET: ${SECRET}
    ports:
      - "80:80"
